export type Locale = "et" | "ru";

const common = {
  company: "Tark Ekspert Grupp OÜ",
  phone: "+372 5683 9913",
  phoneHref: "tel:+37256839913",
  email: "info@tarkekspertgrupp.ee",
  endpoint: process.env.NEXT_PUBLIC_LEAD_ENDPOINT ?? "https://tarkekspertgrupp.ee/send.php",
  projectNames: ["Astangu 44 KÜ", "Kihnu tn 10", "Madala tn 5 KÜ", "Pirni 4", "Raadiku tn 4 KÜ", "Tammsaare tee 76", "Pirni 6a KÜ", "Lagle pst 6a"],
  gallery: ["work-04.jpg","work-05.jpg","work-03-insert.jpg","work-06.jpg","work-facade-final-01.jpg","work-facade-final-02.jpg","work-facade-final-03.jpg","work-07.jpg","work-08.jpg","work-door-01.jpg","work-09.jpg","work-10.jpg","work-stairs-before.jpg","work-stairs-after.jpg","work-11.jpg","work-12.jpg","work-13.jpg","work-15.jpg","work-roof-extra-02.jpg","work-16.jpg","work-17.jpg","work-18.jpg","work-19.jpg","work-20.jpg","work-23.jpg"],
};

export const content = {
  et: {
    ...common,
    langName:"ET", otherLang:"RU", otherHref:"/ru",
    nav:[['Teenused','#teenused'],['Meist','#meist'],['Tööprotsess','#protsess'],['Objektid','#objektid'],['Kontakt','#kontakt']] as const,
    request:"Küsi pakkumist", eyebrow:"Ehitus ja remont · üle Eesti",
    heroTitle:"Ehitus- ja remonditööd võtmed kätte.",
    heroText:"Üks vastutav meeskond alates objekti ülevaatusest kuni tööde ja dokumentatsiooni üleandmiseni.",
    heroPrimary:"Arutame teie objekti", heroSecondary:"Vaata tehtud töid",
    proof:["Selge tööplaan","Võtmed kätte","Üle Eesti"],
    stats:[['8+','aastat praktilist kogemust'],['50+','valminud eri mahuga objekti'],['1','meeskond mõõtmisest üleandmiseni']],
    servicesLabel:"Mida teeme", servicesTitle:"Kõik vajalik ühelt ehituspartnerilt.",
    services:[
      ['Majade ehitus','Vundamendid, seinad, vahelaed, katused, juurdeehitused, garaažid ja abihooned.'],
      ['Remont ja viimistlustööd','Ettevalmistus ja lõppviimistlus, plaatimine, kipsplaaditööd, pahteldus, värvimine, põrandad ja laed.'],
      ['Katused ja fassaadid','Katuste paigaldus ja remont, fassaadide soojustamine, viimistlus ning vihmaveesüsteemid.'],
      ['Inseneritööd','Elekter, torutööd, ruumide ettevalmistus, lammutustööd ja komplekssed tööd objektil.'],
      ['Korteriühistutele','Trepikodade, ühiskasutatavate ruumide, fassaadide, katuste ja teiste elamuosade remont ning hooldus.'],
    ],
    aboutLabel:"Ettevõttest", aboutTitle:"Läbipaistev plaan. Selge vastutus. Korralik tulemus.",
    aboutText:["Tark Ekspert Grupp OÜ on väike ehitusettevõte, mistõttu on iga objekt meile oluline. Enne tööde algust vaatame objekti üle, arutame läbi ülesanded, materjalid, tähtajad ja eelarve.","Meile võib usaldada nii ühe tööetapi kui ka tervikliku tööde paketi. Hindame korda objektil, selget suhtlust ja tulemust, mille üle võib uhke olla."],
    benefits:[['Objekti ülevaatus','Konsultatsioon ja tööde esialgne hindamine.'],['Selge hinnapakkumine','Töömahud, materjalid ja maksumus enne alustamist.'],['Terviklik lähenemine','Üks tööliik või kogu objekt võtmed kätte.'],['Korralik üleandmine','Kontroll, korrastatud töökoht ja vajalik dokumentatsioon.']],
    processLabel:"Tööprotsess", processTitle:"Kontaktist valmis tulemuseni.",
    process:['Kirjeldate ülesannet ja saadate päringu.','Tuleme kohale, vaatame objekti üle ja täpsustame detailid.','Lepime kokku hinna, tähtajad ja materjalid.','Teostame tööd ning anname objekti üle koos dokumentatsiooniga.'],
    projectsLabel:"Valminud objektid", projectsTitle:"Tööd, mis räägivad enda eest.", projectsText:"Näited tehtud töödest elamu-, äri- ja ühiskasutatavates hooneosades.",
    galleryLabel:"25 fotot · reaalsed objektid", galleryTitle:"Valitud tööd üle Eesti",
    contactLabel:"Räägime teie objektist", contactTitle:"Küsige konsultatsiooni ja selget hinnapakkumist.", contactText:"Helistage või täitke lühike vorm. Vaatame ülesande üle ja aitame paika panna tööde järjekorra.",
    formTitle:"Kirjeldage oma ülesannet", name:"Teie nimi", phoneLabel:"Telefon", emailLabel:"Email", location:"Linn või objekti aadress", message:"Mida on vaja teha?", captcha:"Rämpsposti kaitse", submit:"Saada päring", formNote:"Päring saadetakse Tark Ekspert Grupp OÜ olemasoleva turvalise vormi kaudu.",
    details:['Registrikood: 12741049','Registreerimise kuupäev: 23.10.2014','KMKR nr: EE102776562','Tegevusala: üldehitustööd','E-L: 9:00–18:00'],
    privacy:"Privaatsus", footer:"Ehitus, remont ja viimistlus üle Eesti.",
  },
  ru: {
    ...common,
    langName:"RU", otherLang:"ET", otherHref:"/",
    nav:[['Услуги','#teenused'],['О нас','#meist'],['Процесс','#protsess'],['Объекты','#objektid'],['Контакты','#kontakt']] as const,
    request:"Запросить смету", eyebrow:"Строительство и ремонт · по всей Эстонии",
    heroTitle:"Строительные и ремонтные работы под ключ.",
    heroText:"Одна ответственная команда — от осмотра объекта до сдачи работ и документации.",
    heroPrimary:"Обсудить объект", heroSecondary:"Смотреть работы",
    proof:["Понятный план","Объекты под ключ","По всей Эстонии"],
    stats:[['8+','лет практического опыта'],['50+','завершённых объектов'],['1','команда от замера до сдачи']],
    servicesLabel:"Что мы делаем", servicesTitle:"Всё необходимое у одного строительного партнёра.",
    services:[
      ['Строительство домов','Фундаменты, стены, перекрытия, крыши, пристройки, гаражи и хозяйственные постройки.'],
      ['Ремонт и отделка','Подготовительные и финишные работы, плитка, гипсокартон, шпаклёвка, покраска, полы и потолки.'],
      ['Кровля и фасады','Монтаж и ремонт кровли, утепление фасадов, отделка и водосточные системы.'],
      ['Инженерные работы','Электрика, сантехника, подготовка помещений, демонтаж и комплексные задачи.'],
      ['Для квартирных товариществ','Ремонт и обслуживание подъездов, общих помещений, фасадов, кровли и других частей дома.'],
    ],
    aboutLabel:"О компании", aboutTitle:"Прозрачный план. Понятная ответственность. Аккуратный результат.",
    aboutText:["Tark Ekspert Grupp OÜ — небольшая строительная компания, поэтому каждый объект для нас важен. До начала работ мы осматриваем объект, обсуждаем задачи, материалы, сроки и бюджет.","Нам можно доверить отдельный этап или полный комплекс работ. Мы ценим порядок на объекте, ясное общение и результат, которым можно гордиться."],
    benefits:[['Выезд на объект','Консультация и предварительная оценка работ.'],['Понятная смета','Объёмы, материалы и стоимость до начала работ.'],['Комплексный подход','Один вид работ или весь объект под ключ.'],['Аккуратная сдача','Проверка, порядок и необходимая документация.']],
    processLabel:"Как работаем", processTitle:"От первого контакта до готового результата.",
    process:['Вы описываете задачу и отправляете запрос.','Мы приезжаем, осматриваем объект и уточняем детали.','Согласовываем стоимость, сроки и материалы.','Выполняем работы и сдаём объект с документацией.'],
    projectsLabel:"Выполненные объекты", projectsTitle:"Работы, которые говорят сами за себя.", projectsText:"Примеры выполненных работ в жилых, коммерческих и общедомовых помещениях.",
    galleryLabel:"25 фотографий · реальные объекты", galleryTitle:"Избранные работы по Эстонии",
    contactLabel:"Поговорим о вашем объекте", contactTitle:"Получите консультацию и понятную смету.", contactText:"Позвоните или заполните короткую форму. Мы оценим задачу и поможем определить порядок работ.",
    formTitle:"Опишите вашу задачу", name:"Ваше имя", phoneLabel:"Телефон", emailLabel:"Email", location:"Город или адрес объекта", message:"Что нужно сделать?", captcha:"Защита от спама", submit:"Отправить запрос", formNote:"Запрос отправляется через существующую защищённую форму Tark Ekspert Grupp OÜ.",
    details:['Регистрационный номер: 12741049','Дата регистрации: 23.10.2014','НДС номер: EE102776562','Сфера деятельности: общестроительные работы','Пн-Сб: 9:00–18:00'],
    privacy:"Конфиденциальность", footer:"Строительство, ремонт и отделка по всей Эстонии.",
  },
} as const;

export function getContent(locale:Locale){ return content[locale]; }
